#! /bin/sh

set -e

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi

# Add missing directories
mkdir -p lib
mkdir -p modules
./mkmkfile.sh PARLIB none GRAPHICS none PARALLEL sequential F90 gfortran C gcc
make
